// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/user/core/ports/user_token.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/user/core/ports/user_token.go -destination=internal/app/user/core/service/mocks/mock_user_token.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/app/user/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserTokenRepository is a mock of UserTokenRepository interface.
type MockUserTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockUserTokenRepositoryMockRecorder is the mock recorder for MockUserTokenRepository.
type MockUserTokenRepositoryMockRecorder struct {
	mock *MockUserTokenRepository
}

// NewMockUserTokenRepository creates a new mock instance.
func NewMockUserTokenRepository(ctrl *gomock.Controller) *MockUserTokenRepository {
	mock := &MockUserTokenRepository{ctrl: ctrl}
	mock.recorder = &MockUserTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTokenRepository) EXPECT() *MockUserTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteTokenByUserID mocks base method.
func (m *MockUserTokenRepository) DeleteTokenByUserID(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTokenByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTokenByUserID indicates an expected call of DeleteTokenByUserID.
func (mr *MockUserTokenRepositoryMockRecorder) DeleteTokenByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTokenByUserID", reflect.TypeOf((*MockUserTokenRepository)(nil).DeleteTokenByUserID), ctx, userID)
}

// GetTokenByUserID mocks base method.
func (m *MockUserTokenRepository) GetTokenByUserID(ctx context.Context, userID int) (*domain.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByUserID indicates an expected call of GetTokenByUserID.
func (mr *MockUserTokenRepositoryMockRecorder) GetTokenByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByUserID", reflect.TypeOf((*MockUserTokenRepository)(nil).GetTokenByUserID), ctx, userID)
}

// StoreToken mocks base method.
func (m *MockUserTokenRepository) StoreToken(ctx context.Context, token *domain.UserToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreToken indicates an expected call of StoreToken.
func (mr *MockUserTokenRepositoryMockRecorder) StoreToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreToken", reflect.TypeOf((*MockUserTokenRepository)(nil).StoreToken), ctx, token)
}
