basePath: /
definitions:
  github_com_billykore_project-one_internal_api_dto.CreatePostRequest:
    properties:
      content:
        minLength: 10
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    required:
    - content
    - title
    type: object
  github_com_billykore_project-one_internal_api_dto.CreatePostResponse:
    properties:
      id:
        type: integer
      message:
        type: string
    type: object
  github_com_billykore_project-one_internal_api_dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github_com_billykore_project-one_internal_api_dto.FollowData:
    properties:
      followed_at:
        type: string
      followed_user_id:
        type: integer
    type: object
  github_com_billykore_project-one_internal_api_dto.FollowResponse:
    properties:
      data:
        $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.FollowData'
      message:
        type: string
    type: object
  github_com_billykore_project-one_internal_api_dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  github_com_billykore_project-one_internal_api_dto.LoginResponse:
    properties:
      message:
        type: string
    type: object
  github_com_billykore_project-one_internal_api_dto.LogoutResponse:
    properties:
      message:
        type: string
    type: object
  github_com_billykore_project-one_internal_api_dto.PostResponse:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      message:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
  github_com_billykore_project-one_internal_api_dto.RegisterRequest:
    properties:
      email:
        type: string
      first_name:
        minLength: 3
        type: string
      last_name:
        minLength: 3
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  github_com_billykore_project-one_internal_api_dto.RegisterResponse:
    properties:
      message:
        type: string
    type: object
  github_com_billykore_project-one_internal_api_dto.UpdatePostRequest:
    properties:
      content:
        type: string
      title:
        type: string
    type: object
  github_com_billykore_project-one_internal_api_dto.UserResponse:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API server for the User Service.
  title: User Service API
  version: "1.0"
paths:
  /posts:
    get:
      description: Retrieve all posts for the authenticated user.
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.PostResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get user posts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: Create a new post for the authenticated user.
      parameters:
      - description: Post details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.CreatePostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.CreatePostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create post
      tags:
      - posts
  /posts/{id}:
    delete:
      description: Soft delete a post for the authenticated user.
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete post
      tags:
      - posts
    get:
      description: Retrieve a specific post by its ID.
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.PostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      summary: Get post by ID
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: Update an existing post for the authenticated user.
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Post details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.UpdatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.PostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update post
      tags:
      - posts
  /users/{userId}/follow:
    post:
      consumes:
      - application/json
      description: Allows an authenticated user to follow another user.
      parameters:
      - description: User ID to follow
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.FollowResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Follow a user
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return access and refresh tokens via HttpOnly
        cookies.
      parameters:
      - description: Login credentials
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      summary: Login
      tags:
      - users
  /users/logout:
    post:
      consumes:
      - application/json
      description: Invalidate the current user's session.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.LogoutResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Logout
      tags:
      - users
  /users/me:
    get:
      consumes:
      - application/json
      description: Get the profile of the currently authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: Create a new user account.
      parameters:
      - description: User registration details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_billykore_project-one_internal_api_dto.ErrorResponse'
      summary: Register
      tags:
      - users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
