// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/follow.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/follow.go -destination=internal/core/usecase/mocks/mock_follow.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFollowRepository is a mock of FollowRepository interface.
type MockFollowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFollowRepositoryMockRecorder
	isgomock struct{}
}

// MockFollowRepositoryMockRecorder is the mock recorder for MockFollowRepository.
type MockFollowRepositoryMockRecorder struct {
	mock *MockFollowRepository
}

// NewMockFollowRepository creates a new mock instance.
func NewMockFollowRepository(ctrl *gomock.Controller) *MockFollowRepository {
	mock := &MockFollowRepository{ctrl: ctrl}
	mock.recorder = &MockFollowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowRepository) EXPECT() *MockFollowRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFollowRepository) Create(ctx context.Context, follow *domain.Follow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, follow)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFollowRepositoryMockRecorder) Create(ctx, follow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFollowRepository)(nil).Create), ctx, follow)
}

// IsFollowing mocks base method.
func (m *MockFollowRepository) IsFollowing(ctx context.Context, followerID, followedID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowing", ctx, followerID, followedID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowing indicates an expected call of IsFollowing.
func (mr *MockFollowRepositoryMockRecorder) IsFollowing(ctx, followerID, followedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowing", reflect.TypeOf((*MockFollowRepository)(nil).IsFollowing), ctx, followerID, followedID)
}

// MockFollowUseCase is a mock of FollowUseCase interface.
type MockFollowUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFollowUseCaseMockRecorder
	isgomock struct{}
}

// MockFollowUseCaseMockRecorder is the mock recorder for MockFollowUseCase.
type MockFollowUseCaseMockRecorder struct {
	mock *MockFollowUseCase
}

// NewMockFollowUseCase creates a new mock instance.
func NewMockFollowUseCase(ctrl *gomock.Controller) *MockFollowUseCase {
	mock := &MockFollowUseCase{ctrl: ctrl}
	mock.recorder = &MockFollowUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowUseCase) EXPECT() *MockFollowUseCaseMockRecorder {
	return m.recorder
}

// Follow mocks base method.
func (m *MockFollowUseCase) Follow(ctx context.Context, followerID, followedID int) (*domain.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, followerID, followedID)
	ret0, _ := ret[0].(*domain.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowUseCaseMockRecorder) Follow(ctx, followerID, followedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollowUseCase)(nil).Follow), ctx, followerID, followedID)
}
