// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/like.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/like.go -destination=internal/core/usecase/mocks/mock_like.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLikeRepository is a mock of LikeRepository interface.
type MockLikeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLikeRepositoryMockRecorder
	isgomock struct{}
}

// MockLikeRepositoryMockRecorder is the mock recorder for MockLikeRepository.
type MockLikeRepositoryMockRecorder struct {
	mock *MockLikeRepository
}

// NewMockLikeRepository creates a new mock instance.
func NewMockLikeRepository(ctrl *gomock.Controller) *MockLikeRepository {
	mock := &MockLikeRepository{ctrl: ctrl}
	mock.recorder = &MockLikeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeRepository) EXPECT() *MockLikeRepositoryMockRecorder {
	return m.recorder
}

// CountByPostID mocks base method.
func (m *MockLikeRepository) CountByPostID(ctx context.Context, postID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByPostID", ctx, postID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByPostID indicates an expected call of CountByPostID.
func (mr *MockLikeRepositoryMockRecorder) CountByPostID(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByPostID", reflect.TypeOf((*MockLikeRepository)(nil).CountByPostID), ctx, postID)
}

// Create mocks base method.
func (m *MockLikeRepository) Create(ctx context.Context, like *domain.Like) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, like)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLikeRepositoryMockRecorder) Create(ctx, like any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLikeRepository)(nil).Create), ctx, like)
}

// Delete mocks base method.
func (m *MockLikeRepository) Delete(ctx context.Context, postID int, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, postID, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLikeRepositoryMockRecorder) Delete(ctx, postID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLikeRepository)(nil).Delete), ctx, postID, username)
}

// Exists mocks base method.
func (m *MockLikeRepository) Exists(ctx context.Context, postID int, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, postID, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockLikeRepositoryMockRecorder) Exists(ctx, postID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockLikeRepository)(nil).Exists), ctx, postID, username)
}

// MockLikeUseCase is a mock of LikeUseCase interface.
type MockLikeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockLikeUseCaseMockRecorder
	isgomock struct{}
}

// MockLikeUseCaseMockRecorder is the mock recorder for MockLikeUseCase.
type MockLikeUseCaseMockRecorder struct {
	mock *MockLikeUseCase
}

// NewMockLikeUseCase creates a new mock instance.
func NewMockLikeUseCase(ctrl *gomock.Controller) *MockLikeUseCase {
	mock := &MockLikeUseCase{ctrl: ctrl}
	mock.recorder = &MockLikeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeUseCase) EXPECT() *MockLikeUseCaseMockRecorder {
	return m.recorder
}

// GetLikeStatus mocks base method.
func (m *MockLikeUseCase) GetLikeStatus(ctx context.Context, postID int, username string) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeStatus", ctx, postID, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLikeStatus indicates an expected call of GetLikeStatus.
func (mr *MockLikeUseCaseMockRecorder) GetLikeStatus(ctx, postID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeStatus", reflect.TypeOf((*MockLikeUseCase)(nil).GetLikeStatus), ctx, postID, username)
}

// ToggleLike mocks base method.
func (m *MockLikeUseCase) ToggleLike(ctx context.Context, postID int, username string) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleLike", ctx, postID, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ToggleLike indicates an expected call of ToggleLike.
func (mr *MockLikeUseCaseMockRecorder) ToggleLike(ctx, postID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleLike", reflect.TypeOf((*MockLikeUseCase)(nil).ToggleLike), ctx, postID, username)
}
