// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/token.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/token.go -destination=internal/core/usecase/mocks/mock_token.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteTokenByUsername mocks base method.
func (m *MockTokenRepository) DeleteTokenByUsername(ctx context.Context, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTokenByUsername", ctx, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTokenByUsername indicates an expected call of DeleteTokenByUsername.
func (mr *MockTokenRepositoryMockRecorder) DeleteTokenByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTokenByUsername", reflect.TypeOf((*MockTokenRepository)(nil).DeleteTokenByUsername), ctx, username)
}

// GetTokenByUsername mocks base method.
func (m *MockTokenRepository) GetTokenByUsername(ctx context.Context, username string) (*domain.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByUsername indicates an expected call of GetTokenByUsername.
func (mr *MockTokenRepositoryMockRecorder) GetTokenByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByUsername", reflect.TypeOf((*MockTokenRepository)(nil).GetTokenByUsername), ctx, username)
}

// StoreToken mocks base method.
func (m *MockTokenRepository) StoreToken(ctx context.Context, token *domain.UserToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreToken indicates an expected call of StoreToken.
func (mr *MockTokenRepositoryMockRecorder) StoreToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreToken", reflect.TypeOf((*MockTokenRepository)(nil).StoreToken), ctx, token)
}
