// Code generated by MockGen. DO NOT EDIT.
// Source: internal/identity/ports/token.go
//
// Generated by this command:
//
//	mockgen -source=internal/identity/ports/token.go -destination=internal/testkit/mocks/mock_identity_token.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/identity/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteTokensByUserID mocks base method.
func (m *MockTokenRepository) DeleteTokensByUserID(ctx context.Context, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTokensByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTokensByUserID indicates an expected call of DeleteTokensByUserID.
func (mr *MockTokenRepositoryMockRecorder) DeleteTokensByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTokensByUserID", reflect.TypeOf((*MockTokenRepository)(nil).DeleteTokensByUserID), ctx, userID)
}

// IsActive mocks base method.
func (m *MockTokenRepository) IsActive(ctx context.Context, token string, userID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsActive", ctx, token, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsActive indicates an expected call of IsActive.
func (mr *MockTokenRepositoryMockRecorder) IsActive(ctx, token, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsActive", reflect.TypeOf((*MockTokenRepository)(nil).IsActive), ctx, token, userID)
}

// StoreToken mocks base method.
func (m *MockTokenRepository) StoreToken(ctx context.Context, token *domain.UserToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreToken indicates an expected call of StoreToken.
func (mr *MockTokenRepositoryMockRecorder) StoreToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreToken", reflect.TypeOf((*MockTokenRepository)(nil).StoreToken), ctx, token)
}
