// Code generated by MockGen. DO NOT EDIT.
// Source: internal/social/ports/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/social/ports/dependencies.go -destination=internal/testkit/mocks/mock_social_dependencies.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/identity/domain"
	valueobject "github.com/billykore/project-one/internal/platform/pagination"
	domain0 "github.com/billykore/project-one/internal/publishing/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountLookup is a mock of AccountLookup interface.
type MockAccountLookup struct {
	ctrl     *gomock.Controller
	recorder *MockAccountLookupMockRecorder
	isgomock struct{}
}

// MockAccountLookupMockRecorder is the mock recorder for MockAccountLookup.
type MockAccountLookupMockRecorder struct {
	mock *MockAccountLookup
}

// NewMockAccountLookup creates a new mock instance.
func NewMockAccountLookup(ctrl *gomock.Controller) *MockAccountLookup {
	mock := &MockAccountLookup{ctrl: ctrl}
	mock.recorder = &MockAccountLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountLookup) EXPECT() *MockAccountLookupMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockAccountLookup) GetUserByID(ctx context.Context, id int) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAccountLookupMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAccountLookup)(nil).GetUserByID), ctx, id)
}

// GetUserByUsername mocks base method.
func (m *MockAccountLookup) GetUserByUsername(ctx context.Context, username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockAccountLookupMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockAccountLookup)(nil).GetUserByUsername), ctx, username)
}

// MockTimelineReader is a mock of TimelineReader interface.
type MockTimelineReader struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineReaderMockRecorder
	isgomock struct{}
}

// MockTimelineReaderMockRecorder is the mock recorder for MockTimelineReader.
type MockTimelineReaderMockRecorder struct {
	mock *MockTimelineReader
}

// NewMockTimelineReader creates a new mock instance.
func NewMockTimelineReader(ctrl *gomock.Controller) *MockTimelineReader {
	mock := &MockTimelineReader{ctrl: ctrl}
	mock.recorder = &MockTimelineReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimelineReader) EXPECT() *MockTimelineReaderMockRecorder {
	return m.recorder
}

// GetFeed mocks base method.
func (m *MockTimelineReader) GetFeed(ctx context.Context, userIDs []int, cursor *valueobject.Cursor, limit int) ([]*domain0.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", ctx, userIDs, cursor, limit)
	ret0, _ := ret[0].([]*domain0.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockTimelineReaderMockRecorder) GetFeed(ctx, userIDs, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockTimelineReader)(nil).GetFeed), ctx, userIDs, cursor, limit)
}
