// Code generated by MockGen. DO NOT EDIT.
// Source: internal/publishing/ports/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/publishing/ports/dependencies.go -destination=internal/testkit/mocks/mock_publishing_dependencies.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/featureflags/domain"
	domain0 "github.com/billykore/project-one/internal/identity/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserLookup is a mock of UserLookup interface.
type MockUserLookup struct {
	ctrl     *gomock.Controller
	recorder *MockUserLookupMockRecorder
	isgomock struct{}
}

// MockUserLookupMockRecorder is the mock recorder for MockUserLookup.
type MockUserLookupMockRecorder struct {
	mock *MockUserLookup
}

// NewMockUserLookup creates a new mock instance.
func NewMockUserLookup(ctrl *gomock.Controller) *MockUserLookup {
	mock := &MockUserLookup{ctrl: ctrl}
	mock.recorder = &MockUserLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLookup) EXPECT() *MockUserLookupMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockUserLookup) GetUserByID(ctx context.Context, id int) (*domain0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserLookupMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserLookup)(nil).GetUserByID), ctx, id)
}

// MockFeatureEvaluator is a mock of FeatureEvaluator interface.
type MockFeatureEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureEvaluatorMockRecorder
	isgomock struct{}
}

// MockFeatureEvaluatorMockRecorder is the mock recorder for MockFeatureEvaluator.
type MockFeatureEvaluatorMockRecorder struct {
	mock *MockFeatureEvaluator
}

// NewMockFeatureEvaluator creates a new mock instance.
func NewMockFeatureEvaluator(ctrl *gomock.Controller) *MockFeatureEvaluator {
	mock := &MockFeatureEvaluator{ctrl: ctrl}
	mock.recorder = &MockFeatureEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureEvaluator) EXPECT() *MockFeatureEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockFeatureEvaluator) Evaluate(ctx context.Context, key, username string) domain.FeatureFlagDecision {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, key, username)
	ret0, _ := ret[0].(domain.FeatureFlagDecision)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockFeatureEvaluatorMockRecorder) Evaluate(ctx, key, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockFeatureEvaluator)(nil).Evaluate), ctx, key, username)
}
