// Code generated by MockGen. DO NOT EDIT.
// Source: internal/notifications/ports/dependencies.go
//
// Generated by this command:
//
//	mockgen -source=internal/notifications/ports/dependencies.go -destination=internal/testkit/mocks/mock_notifications_dependencies.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/identity/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockActorLookup is a mock of ActorLookup interface.
type MockActorLookup struct {
	ctrl     *gomock.Controller
	recorder *MockActorLookupMockRecorder
	isgomock struct{}
}

// MockActorLookupMockRecorder is the mock recorder for MockActorLookup.
type MockActorLookupMockRecorder struct {
	mock *MockActorLookup
}

// NewMockActorLookup creates a new mock instance.
func NewMockActorLookup(ctrl *gomock.Controller) *MockActorLookup {
	mock := &MockActorLookup{ctrl: ctrl}
	mock.recorder = &MockActorLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorLookup) EXPECT() *MockActorLookupMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockActorLookup) GetUserByID(ctx context.Context, id int) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockActorLookupMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockActorLookup)(nil).GetUserByID), ctx, id)
}
