// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/feed.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/feed.go -destination=internal/core/ports/mocks/mock_feed.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/billykore/project-one/internal/core/ports"
	pagination "github.com/billykore/project-one/internal/pkg/pagination"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedUseCase is a mock of FeedUseCase interface.
type MockFeedUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFeedUseCaseMockRecorder
	isgomock struct{}
}

// MockFeedUseCaseMockRecorder is the mock recorder for MockFeedUseCase.
type MockFeedUseCaseMockRecorder struct {
	mock *MockFeedUseCase
}

// NewMockFeedUseCase creates a new mock instance.
func NewMockFeedUseCase(ctrl *gomock.Controller) *MockFeedUseCase {
	mock := &MockFeedUseCase{ctrl: ctrl}
	mock.recorder = &MockFeedUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedUseCase) EXPECT() *MockFeedUseCaseMockRecorder {
	return m.recorder
}

// GetFeed mocks base method.
func (m *MockFeedUseCase) GetFeed(ctx context.Context, username string, cursor *pagination.Cursor, limit int) (*ports.FeedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", ctx, username, cursor, limit)
	ret0, _ := ret[0].(*ports.FeedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockFeedUseCaseMockRecorder) GetFeed(ctx, username, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockFeedUseCase)(nil).GetFeed), ctx, username, cursor, limit)
}
