// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/follow.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/follow.go -destination=internal/core/ports/mocks/mock_follow.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/core/domain"
	ports "github.com/billykore/project-one/internal/core/ports"
	valueobject "github.com/billykore/project-one/internal/core/valueobject"
	gomock "go.uber.org/mock/gomock"
)

// MockFollowRepository is a mock of FollowRepository interface.
type MockFollowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFollowRepositoryMockRecorder
	isgomock struct{}
}

// MockFollowRepositoryMockRecorder is the mock recorder for MockFollowRepository.
type MockFollowRepositoryMockRecorder struct {
	mock *MockFollowRepository
}

// NewMockFollowRepository creates a new mock instance.
func NewMockFollowRepository(ctrl *gomock.Controller) *MockFollowRepository {
	mock := &MockFollowRepository{ctrl: ctrl}
	mock.recorder = &MockFollowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowRepository) EXPECT() *MockFollowRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFollowRepository) Create(ctx context.Context, follow *domain.Follow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, follow)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFollowRepositoryMockRecorder) Create(ctx, follow any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFollowRepository)(nil).Create), ctx, follow)
}

// Delete mocks base method.
func (m *MockFollowRepository) Delete(ctx context.Context, followerID, followedID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, followerID, followedID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFollowRepositoryMockRecorder) Delete(ctx, followerID, followedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFollowRepository)(nil).Delete), ctx, followerID, followedID)
}

// GetFollowedUserIDs mocks base method.
func (m *MockFollowRepository) GetFollowedUserIDs(ctx context.Context, followerID int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowedUserIDs", ctx, followerID)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowedUserIDs indicates an expected call of GetFollowedUserIDs.
func (mr *MockFollowRepositoryMockRecorder) GetFollowedUserIDs(ctx, followerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowedUserIDs", reflect.TypeOf((*MockFollowRepository)(nil).GetFollowedUserIDs), ctx, followerID)
}

// GetFollowers mocks base method.
func (m *MockFollowRepository) GetFollowers(ctx context.Context, followedID int, cursor *valueobject.Cursor, limit int) ([]domain.Follower, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowers", ctx, followedID, cursor, limit)
	ret0, _ := ret[0].([]domain.Follower)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowers indicates an expected call of GetFollowers.
func (mr *MockFollowRepositoryMockRecorder) GetFollowers(ctx, followedID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowers", reflect.TypeOf((*MockFollowRepository)(nil).GetFollowers), ctx, followedID, cursor, limit)
}

// GetFollowing mocks base method.
func (m *MockFollowRepository) GetFollowing(ctx context.Context, followerID int, cursor *valueobject.Cursor, limit int) ([]domain.Following, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowing", ctx, followerID, cursor, limit)
	ret0, _ := ret[0].([]domain.Following)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowing indicates an expected call of GetFollowing.
func (mr *MockFollowRepositoryMockRecorder) GetFollowing(ctx, followerID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowing", reflect.TypeOf((*MockFollowRepository)(nil).GetFollowing), ctx, followerID, cursor, limit)
}

// MockFollowUseCase is a mock of FollowUseCase interface.
type MockFollowUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFollowUseCaseMockRecorder
	isgomock struct{}
}

// MockFollowUseCaseMockRecorder is the mock recorder for MockFollowUseCase.
type MockFollowUseCaseMockRecorder struct {
	mock *MockFollowUseCase
}

// NewMockFollowUseCase creates a new mock instance.
func NewMockFollowUseCase(ctrl *gomock.Controller) *MockFollowUseCase {
	mock := &MockFollowUseCase{ctrl: ctrl}
	mock.recorder = &MockFollowUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowUseCase) EXPECT() *MockFollowUseCaseMockRecorder {
	return m.recorder
}

// Follow mocks base method.
func (m *MockFollowUseCase) Follow(ctx context.Context, actor *domain.User, followedUsername string) (*domain.Follow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Follow", ctx, actor, followedUsername)
	ret0, _ := ret[0].(*domain.Follow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Follow indicates an expected call of Follow.
func (mr *MockFollowUseCaseMockRecorder) Follow(ctx, actor, followedUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Follow", reflect.TypeOf((*MockFollowUseCase)(nil).Follow), ctx, actor, followedUsername)
}

// GetFollowers mocks base method.
func (m *MockFollowUseCase) GetFollowers(ctx context.Context, followedUsername string, cursor *valueobject.Cursor, limit int) (*ports.FollowersPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowers", ctx, followedUsername, cursor, limit)
	ret0, _ := ret[0].(*ports.FollowersPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowers indicates an expected call of GetFollowers.
func (mr *MockFollowUseCaseMockRecorder) GetFollowers(ctx, followedUsername, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowers", reflect.TypeOf((*MockFollowUseCase)(nil).GetFollowers), ctx, followedUsername, cursor, limit)
}

// GetFollowing mocks base method.
func (m *MockFollowUseCase) GetFollowing(ctx context.Context, followerUsername string, cursor *valueobject.Cursor, limit int) (*ports.FollowingPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowing", ctx, followerUsername, cursor, limit)
	ret0, _ := ret[0].(*ports.FollowingPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowing indicates an expected call of GetFollowing.
func (mr *MockFollowUseCaseMockRecorder) GetFollowing(ctx, followerUsername, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowing", reflect.TypeOf((*MockFollowUseCase)(nil).GetFollowing), ctx, followerUsername, cursor, limit)
}

// Unfollow mocks base method.
func (m *MockFollowUseCase) Unfollow(ctx context.Context, actor *domain.User, followedUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unfollow", ctx, actor, followedUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unfollow indicates an expected call of Unfollow.
func (mr *MockFollowUseCaseMockRecorder) Unfollow(ctx, actor, followedUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unfollow", reflect.TypeOf((*MockFollowUseCase)(nil).Unfollow), ctx, actor, followedUsername)
}
