// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/like.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/like.go -destination=internal/core/ports/mocks/mock_like.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLikeRepository is a mock of LikeRepository interface.
type MockLikeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLikeRepositoryMockRecorder
	isgomock struct{}
}

// MockLikeRepositoryMockRecorder is the mock recorder for MockLikeRepository.
type MockLikeRepositoryMockRecorder struct {
	mock *MockLikeRepository
}

// NewMockLikeRepository creates a new mock instance.
func NewMockLikeRepository(ctrl *gomock.Controller) *MockLikeRepository {
	mock := &MockLikeRepository{ctrl: ctrl}
	mock.recorder = &MockLikeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikeRepository) EXPECT() *MockLikeRepositoryMockRecorder {
	return m.recorder
}

// CountByPostID mocks base method.
func (m *MockLikeRepository) CountByPostID(ctx context.Context, postID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByPostID", ctx, postID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByPostID indicates an expected call of CountByPostID.
func (mr *MockLikeRepositoryMockRecorder) CountByPostID(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByPostID", reflect.TypeOf((*MockLikeRepository)(nil).CountByPostID), ctx, postID)
}

// Create mocks base method.
func (m *MockLikeRepository) Create(ctx context.Context, like *domain.Like) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, like)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLikeRepositoryMockRecorder) Create(ctx, like any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLikeRepository)(nil).Create), ctx, like)
}

// Delete mocks base method.
func (m *MockLikeRepository) Delete(ctx context.Context, postID, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, postID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLikeRepositoryMockRecorder) Delete(ctx, postID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLikeRepository)(nil).Delete), ctx, postID, userID)
}

// Exists mocks base method.
func (m *MockLikeRepository) Exists(ctx context.Context, postID, userID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, postID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockLikeRepositoryMockRecorder) Exists(ctx, postID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockLikeRepository)(nil).Exists), ctx, postID, userID)
}

// SetLiked mocks base method.
func (m *MockLikeRepository) SetLiked(ctx context.Context, postID, userID int, liked bool) (int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLiked", ctx, postID, userID, liked)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetLiked indicates an expected call of SetLiked.
func (mr *MockLikeRepositoryMockRecorder) SetLiked(ctx, postID, userID, liked any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLiked", reflect.TypeOf((*MockLikeRepository)(nil).SetLiked), ctx, postID, userID, liked)
}
