// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/post.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/post.go -destination=internal/core/ports/mocks/mock_post.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/core/domain"
	valueobject "github.com/billykore/project-one/internal/core/valueobject"
	gomock "go.uber.org/mock/gomock"
)

// MockPostCommandRepository is a mock of PostCommandRepository interface.
type MockPostCommandRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostCommandRepositoryMockRecorder
	isgomock struct{}
}

// MockPostCommandRepositoryMockRecorder is the mock recorder for MockPostCommandRepository.
type MockPostCommandRepositoryMockRecorder struct {
	mock *MockPostCommandRepository
}

// NewMockPostCommandRepository creates a new mock instance.
func NewMockPostCommandRepository(ctrl *gomock.Controller) *MockPostCommandRepository {
	mock := &MockPostCommandRepository{ctrl: ctrl}
	mock.recorder = &MockPostCommandRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostCommandRepository) EXPECT() *MockPostCommandRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPostCommandRepository) Delete(ctx context.Context, post *domain.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostCommandRepositoryMockRecorder) Delete(ctx, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostCommandRepository)(nil).Delete), ctx, post)
}

// Load mocks base method.
func (m *MockPostCommandRepository) Load(ctx context.Context, id int) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, id)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockPostCommandRepositoryMockRecorder) Load(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockPostCommandRepository)(nil).Load), ctx, id)
}

// Save mocks base method.
func (m *MockPostCommandRepository) Save(ctx context.Context, post *domain.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPostCommandRepositoryMockRecorder) Save(ctx, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPostCommandRepository)(nil).Save), ctx, post)
}

// MockPostQueryRepository is a mock of PostQueryRepository interface.
type MockPostQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockPostQueryRepositoryMockRecorder is the mock recorder for MockPostQueryRepository.
type MockPostQueryRepositoryMockRecorder struct {
	mock *MockPostQueryRepository
}

// NewMockPostQueryRepository creates a new mock instance.
func NewMockPostQueryRepository(ctrl *gomock.Controller) *MockPostQueryRepository {
	mock := &MockPostQueryRepository{ctrl: ctrl}
	mock.recorder = &MockPostQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostQueryRepository) EXPECT() *MockPostQueryRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockPostQueryRepository) GetByID(ctx context.Context, id int) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPostQueryRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPostQueryRepository)(nil).GetByID), ctx, id)
}

// GetFeed mocks base method.
func (m *MockPostQueryRepository) GetFeed(ctx context.Context, userIDs []int, cursor *valueobject.Cursor, limit int) ([]*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", ctx, userIDs, cursor, limit)
	ret0, _ := ret[0].([]*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockPostQueryRepositoryMockRecorder) GetFeed(ctx, userIDs, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockPostQueryRepository)(nil).GetFeed), ctx, userIDs, cursor, limit)
}

// GetUserPosts mocks base method.
func (m *MockPostQueryRepository) GetUserPosts(ctx context.Context, userID int, cursor *valueobject.Cursor, limit int) ([]*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPosts", ctx, userID, cursor, limit)
	ret0, _ := ret[0].([]*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPosts indicates an expected call of GetUserPosts.
func (mr *MockPostQueryRepositoryMockRecorder) GetUserPosts(ctx, userID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPosts", reflect.TypeOf((*MockPostQueryRepository)(nil).GetUserPosts), ctx, userID, cursor, limit)
}

// MockPostCommandUseCase is a mock of PostCommandUseCase interface.
type MockPostCommandUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostCommandUseCaseMockRecorder
	isgomock struct{}
}

// MockPostCommandUseCaseMockRecorder is the mock recorder for MockPostCommandUseCase.
type MockPostCommandUseCaseMockRecorder struct {
	mock *MockPostCommandUseCase
}

// NewMockPostCommandUseCase creates a new mock instance.
func NewMockPostCommandUseCase(ctrl *gomock.Controller) *MockPostCommandUseCase {
	mock := &MockPostCommandUseCase{ctrl: ctrl}
	mock.recorder = &MockPostCommandUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostCommandUseCase) EXPECT() *MockPostCommandUseCaseMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockPostCommandUseCase) CreatePost(ctx context.Context, user *domain.User, title, content string, tags []string) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, user, title, content, tags)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockPostCommandUseCaseMockRecorder) CreatePost(ctx, user, title, content, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockPostCommandUseCase)(nil).CreatePost), ctx, user, title, content, tags)
}

// DeletePost mocks base method.
func (m *MockPostCommandUseCase) DeletePost(ctx context.Context, userID, postID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockPostCommandUseCaseMockRecorder) DeletePost(ctx, userID, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockPostCommandUseCase)(nil).DeletePost), ctx, userID, postID)
}

// LikePost mocks base method.
func (m *MockPostCommandUseCase) LikePost(ctx context.Context, postID int, username string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikePost", ctx, postID, username)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LikePost indicates an expected call of LikePost.
func (mr *MockPostCommandUseCaseMockRecorder) LikePost(ctx, postID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikePost", reflect.TypeOf((*MockPostCommandUseCase)(nil).LikePost), ctx, postID, username)
}

// UnlikePost mocks base method.
func (m *MockPostCommandUseCase) UnlikePost(ctx context.Context, postID int, username string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikePost", ctx, postID, username)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnlikePost indicates an expected call of UnlikePost.
func (mr *MockPostCommandUseCaseMockRecorder) UnlikePost(ctx, postID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikePost", reflect.TypeOf((*MockPostCommandUseCase)(nil).UnlikePost), ctx, postID, username)
}

// UpdatePost mocks base method.
func (m *MockPostCommandUseCase) UpdatePost(ctx context.Context, userID, postID int, title, content string) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", ctx, userID, postID, title, content)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockPostCommandUseCaseMockRecorder) UpdatePost(ctx, userID, postID, title, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockPostCommandUseCase)(nil).UpdatePost), ctx, userID, postID, title, content)
}

// MockPostQueryUseCase is a mock of PostQueryUseCase interface.
type MockPostQueryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostQueryUseCaseMockRecorder
	isgomock struct{}
}

// MockPostQueryUseCaseMockRecorder is the mock recorder for MockPostQueryUseCase.
type MockPostQueryUseCaseMockRecorder struct {
	mock *MockPostQueryUseCase
}

// NewMockPostQueryUseCase creates a new mock instance.
func NewMockPostQueryUseCase(ctrl *gomock.Controller) *MockPostQueryUseCase {
	mock := &MockPostQueryUseCase{ctrl: ctrl}
	mock.recorder = &MockPostQueryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostQueryUseCase) EXPECT() *MockPostQueryUseCaseMockRecorder {
	return m.recorder
}

// GetLikeStatus mocks base method.
func (m *MockPostQueryUseCase) GetLikeStatus(ctx context.Context, postID int, username string) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikeStatus", ctx, postID, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLikeStatus indicates an expected call of GetLikeStatus.
func (mr *MockPostQueryUseCaseMockRecorder) GetLikeStatus(ctx, postID, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikeStatus", reflect.TypeOf((*MockPostQueryUseCase)(nil).GetLikeStatus), ctx, postID, username)
}

// GetPostByID mocks base method.
func (m *MockPostQueryUseCase) GetPostByID(ctx context.Context, postID int) (*domain.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByID", ctx, postID)
	ret0, _ := ret[0].(*domain.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByID indicates an expected call of GetPostByID.
func (mr *MockPostQueryUseCaseMockRecorder) GetPostByID(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByID", reflect.TypeOf((*MockPostQueryUseCase)(nil).GetPostByID), ctx, postID)
}

// GetPosts mocks base method.
func (m *MockPostQueryUseCase) GetPosts(ctx context.Context, userID int, cursor *valueobject.Cursor, limit int) ([]*domain.Post, *valueobject.Cursor, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", ctx, userID, cursor, limit)
	ret0, _ := ret[0].([]*domain.Post)
	ret1, _ := ret[1].(*valueobject.Cursor)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockPostQueryUseCaseMockRecorder) GetPosts(ctx, userID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockPostQueryUseCase)(nil).GetPosts), ctx, userID, cursor, limit)
}
