// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/health.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/health.go -destination=internal/core/ports/mocks/mock_health.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockDependencyChecker is a mock of DependencyChecker interface.
type MockDependencyChecker struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyCheckerMockRecorder
	isgomock struct{}
}

// MockDependencyCheckerMockRecorder is the mock recorder for MockDependencyChecker.
type MockDependencyCheckerMockRecorder struct {
	mock *MockDependencyChecker
}

// NewMockDependencyChecker creates a new mock instance.
func NewMockDependencyChecker(ctrl *gomock.Controller) *MockDependencyChecker {
	mock := &MockDependencyChecker{ctrl: ctrl}
	mock.recorder = &MockDependencyCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDependencyChecker) EXPECT() *MockDependencyCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockDependencyChecker) Check(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockDependencyCheckerMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockDependencyChecker)(nil).Check), ctx)
}

// Name mocks base method.
func (m *MockDependencyChecker) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDependencyCheckerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDependencyChecker)(nil).Name))
}

// MockHealthObserver is a mock of HealthObserver interface.
type MockHealthObserver struct {
	ctrl     *gomock.Controller
	recorder *MockHealthObserverMockRecorder
	isgomock struct{}
}

// MockHealthObserverMockRecorder is the mock recorder for MockHealthObserver.
type MockHealthObserverMockRecorder struct {
	mock *MockHealthObserver
}

// NewMockHealthObserver creates a new mock instance.
func NewMockHealthObserver(ctrl *gomock.Controller) *MockHealthObserver {
	mock := &MockHealthObserver{ctrl: ctrl}
	mock.recorder = &MockHealthObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthObserver) EXPECT() *MockHealthObserverMockRecorder {
	return m.recorder
}

// ObserveAssessment mocks base method.
func (m *MockHealthObserver) ObserveAssessment(ctx context.Context, assessment domain.HealthAssessment) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveAssessment", ctx, assessment)
}

// ObserveAssessment indicates an expected call of ObserveAssessment.
func (mr *MockHealthObserverMockRecorder) ObserveAssessment(ctx, assessment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveAssessment", reflect.TypeOf((*MockHealthObserver)(nil).ObserveAssessment), ctx, assessment)
}

// MockHTTPMetrics is a mock of HTTPMetrics interface.
type MockHTTPMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPMetricsMockRecorder
	isgomock struct{}
}

// MockHTTPMetricsMockRecorder is the mock recorder for MockHTTPMetrics.
type MockHTTPMetricsMockRecorder struct {
	mock *MockHTTPMetrics
}

// NewMockHTTPMetrics creates a new mock instance.
func NewMockHTTPMetrics(ctrl *gomock.Controller) *MockHTTPMetrics {
	mock := &MockHTTPMetrics{ctrl: ctrl}
	mock.recorder = &MockHTTPMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPMetrics) EXPECT() *MockHTTPMetricsMockRecorder {
	return m.recorder
}

// ObserveRequest mocks base method.
func (m *MockHTTPMetrics) ObserveRequest(ctx context.Context, method, route, statusClass string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveRequest", ctx, method, route, statusClass)
}

// ObserveRequest indicates an expected call of ObserveRequest.
func (mr *MockHTTPMetricsMockRecorder) ObserveRequest(ctx, method, route, statusClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveRequest", reflect.TypeOf((*MockHTTPMetrics)(nil).ObserveRequest), ctx, method, route, statusClass)
}

// ObserveRequestDuration mocks base method.
func (m *MockHTTPMetrics) ObserveRequestDuration(ctx context.Context, method, route string, seconds float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveRequestDuration", ctx, method, route, seconds)
}

// ObserveRequestDuration indicates an expected call of ObserveRequestDuration.
func (mr *MockHTTPMetricsMockRecorder) ObserveRequestDuration(ctx, method, route, seconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveRequestDuration", reflect.TypeOf((*MockHTTPMetrics)(nil).ObserveRequestDuration), ctx, method, route, seconds)
}

// MockHealthAssessor is a mock of HealthAssessor interface.
type MockHealthAssessor struct {
	ctrl     *gomock.Controller
	recorder *MockHealthAssessorMockRecorder
	isgomock struct{}
}

// MockHealthAssessorMockRecorder is the mock recorder for MockHealthAssessor.
type MockHealthAssessorMockRecorder struct {
	mock *MockHealthAssessor
}

// NewMockHealthAssessor creates a new mock instance.
func NewMockHealthAssessor(ctrl *gomock.Controller) *MockHealthAssessor {
	mock := &MockHealthAssessor{ctrl: ctrl}
	mock.recorder = &MockHealthAssessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthAssessor) EXPECT() *MockHealthAssessorMockRecorder {
	return m.recorder
}

// Assess mocks base method.
func (m *MockHealthAssessor) Assess(ctx context.Context) domain.HealthAssessment {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assess", ctx)
	ret0, _ := ret[0].(domain.HealthAssessment)
	return ret0
}

// Assess indicates an expected call of Assess.
func (mr *MockHealthAssessorMockRecorder) Assess(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assess", reflect.TypeOf((*MockHealthAssessor)(nil).Assess), ctx)
}
