// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/feature_flag.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/feature_flag.go -destination=internal/core/ports/mocks/mock_feature_flag.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/billykore/project-one/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFeatureFlagRepository is a mock of FeatureFlagRepository interface.
type MockFeatureFlagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureFlagRepositoryMockRecorder
	isgomock struct{}
}

// MockFeatureFlagRepositoryMockRecorder is the mock recorder for MockFeatureFlagRepository.
type MockFeatureFlagRepositoryMockRecorder struct {
	mock *MockFeatureFlagRepository
}

// NewMockFeatureFlagRepository creates a new mock instance.
func NewMockFeatureFlagRepository(ctrl *gomock.Controller) *MockFeatureFlagRepository {
	mock := &MockFeatureFlagRepository{ctrl: ctrl}
	mock.recorder = &MockFeatureFlagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureFlagRepository) EXPECT() *MockFeatureFlagRepositoryMockRecorder {
	return m.recorder
}

// AppendAudit mocks base method.
func (m *MockFeatureFlagRepository) AppendAudit(ctx context.Context, record *domain.AuditRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAudit", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAudit indicates an expected call of AppendAudit.
func (mr *MockFeatureFlagRepositoryMockRecorder) AppendAudit(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAudit", reflect.TypeOf((*MockFeatureFlagRepository)(nil).AppendAudit), ctx, record)
}

// Archive mocks base method.
func (m *MockFeatureFlagRepository) Archive(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockFeatureFlagRepositoryMockRecorder) Archive(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockFeatureFlagRepository)(nil).Archive), ctx, key)
}

// Create mocks base method.
func (m *MockFeatureFlagRepository) Create(ctx context.Context, flag *domain.FeatureFlag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFeatureFlagRepositoryMockRecorder) Create(ctx, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeatureFlagRepository)(nil).Create), ctx, flag)
}

// GetByKey mocks base method.
func (m *MockFeatureFlagRepository) GetByKey(ctx context.Context, key string) (*domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, key)
	ret0, _ := ret[0].(*domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockFeatureFlagRepositoryMockRecorder) GetByKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockFeatureFlagRepository)(nil).GetByKey), ctx, key)
}

// GetSetting mocks base method.
func (m *MockFeatureFlagRepository) GetSetting(ctx context.Context, flagID int, env domain.Environment) (*domain.EnvironmentSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetting", ctx, flagID, env)
	ret0, _ := ret[0].(*domain.EnvironmentSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetting indicates an expected call of GetSetting.
func (mr *MockFeatureFlagRepositoryMockRecorder) GetSetting(ctx, flagID, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetting", reflect.TypeOf((*MockFeatureFlagRepository)(nil).GetSetting), ctx, flagID, env)
}

// List mocks base method.
func (m *MockFeatureFlagRepository) List(ctx context.Context) ([]domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFeatureFlagRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFeatureFlagRepository)(nil).List), ctx)
}

// ListAudit mocks base method.
func (m *MockFeatureFlagRepository) ListAudit(ctx context.Context, flagID, cursor, limit int) ([]domain.AuditRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAudit", ctx, flagID, cursor, limit)
	ret0, _ := ret[0].([]domain.AuditRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAudit indicates an expected call of ListAudit.
func (mr *MockFeatureFlagRepositoryMockRecorder) ListAudit(ctx, flagID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAudit", reflect.TypeOf((*MockFeatureFlagRepository)(nil).ListAudit), ctx, flagID, cursor, limit)
}

// ListOverrides mocks base method.
func (m *MockFeatureFlagRepository) ListOverrides(ctx context.Context, flagID int, env domain.Environment) ([]domain.UserOverride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOverrides", ctx, flagID, env)
	ret0, _ := ret[0].([]domain.UserOverride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOverrides indicates an expected call of ListOverrides.
func (mr *MockFeatureFlagRepositoryMockRecorder) ListOverrides(ctx, flagID, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOverrides", reflect.TypeOf((*MockFeatureFlagRepository)(nil).ListOverrides), ctx, flagID, env)
}

// ListSettings mocks base method.
func (m *MockFeatureFlagRepository) ListSettings(ctx context.Context, flagID int) ([]domain.EnvironmentSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSettings", ctx, flagID)
	ret0, _ := ret[0].([]domain.EnvironmentSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSettings indicates an expected call of ListSettings.
func (mr *MockFeatureFlagRepositoryMockRecorder) ListSettings(ctx, flagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSettings", reflect.TypeOf((*MockFeatureFlagRepository)(nil).ListSettings), ctx, flagID)
}

// LoadSnapshot mocks base method.
func (m *MockFeatureFlagRepository) LoadSnapshot(ctx context.Context, env domain.Environment) ([]domain.FlagSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSnapshot", ctx, env)
	ret0, _ := ret[0].([]domain.FlagSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSnapshot indicates an expected call of LoadSnapshot.
func (mr *MockFeatureFlagRepositoryMockRecorder) LoadSnapshot(ctx, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSnapshot", reflect.TypeOf((*MockFeatureFlagRepository)(nil).LoadSnapshot), ctx, env)
}

// SetOverrides mocks base method.
func (m *MockFeatureFlagRepository) SetOverrides(ctx context.Context, flagID int, env domain.Environment, includes, excludes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOverrides", ctx, flagID, env, includes, excludes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOverrides indicates an expected call of SetOverrides.
func (mr *MockFeatureFlagRepositoryMockRecorder) SetOverrides(ctx, flagID, env, includes, excludes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOverrides", reflect.TypeOf((*MockFeatureFlagRepository)(nil).SetOverrides), ctx, flagID, env, includes, excludes)
}

// UpdateMetadata mocks base method.
func (m *MockFeatureFlagRepository) UpdateMetadata(ctx context.Context, flag *domain.FeatureFlag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", ctx, flag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockFeatureFlagRepositoryMockRecorder) UpdateMetadata(ctx, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockFeatureFlagRepository)(nil).UpdateMetadata), ctx, flag)
}

// UpsertSetting mocks base method.
func (m *MockFeatureFlagRepository) UpsertSetting(ctx context.Context, setting *domain.EnvironmentSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSetting", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSetting indicates an expected call of UpsertSetting.
func (mr *MockFeatureFlagRepositoryMockRecorder) UpsertSetting(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSetting", reflect.TypeOf((*MockFeatureFlagRepository)(nil).UpsertSetting), ctx, setting)
}

// MockFeatureFlagEvaluator is a mock of FeatureFlagEvaluator interface.
type MockFeatureFlagEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureFlagEvaluatorMockRecorder
	isgomock struct{}
}

// MockFeatureFlagEvaluatorMockRecorder is the mock recorder for MockFeatureFlagEvaluator.
type MockFeatureFlagEvaluatorMockRecorder struct {
	mock *MockFeatureFlagEvaluator
}

// NewMockFeatureFlagEvaluator creates a new mock instance.
func NewMockFeatureFlagEvaluator(ctrl *gomock.Controller) *MockFeatureFlagEvaluator {
	mock := &MockFeatureFlagEvaluator{ctrl: ctrl}
	mock.recorder = &MockFeatureFlagEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureFlagEvaluator) EXPECT() *MockFeatureFlagEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockFeatureFlagEvaluator) Evaluate(ctx context.Context, key, username string) domain.FeatureFlagDecision {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, key, username)
	ret0, _ := ret[0].(domain.FeatureFlagDecision)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockFeatureFlagEvaluatorMockRecorder) Evaluate(ctx, key, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockFeatureFlagEvaluator)(nil).Evaluate), ctx, key, username)
}

// Refresh mocks base method.
func (m *MockFeatureFlagEvaluator) Refresh(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockFeatureFlagEvaluatorMockRecorder) Refresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockFeatureFlagEvaluator)(nil).Refresh), ctx)
}

// MockFeatureFlagUseCase is a mock of FeatureFlagUseCase interface.
type MockFeatureFlagUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureFlagUseCaseMockRecorder
	isgomock struct{}
}

// MockFeatureFlagUseCaseMockRecorder is the mock recorder for MockFeatureFlagUseCase.
type MockFeatureFlagUseCaseMockRecorder struct {
	mock *MockFeatureFlagUseCase
}

// NewMockFeatureFlagUseCase creates a new mock instance.
func NewMockFeatureFlagUseCase(ctrl *gomock.Controller) *MockFeatureFlagUseCase {
	mock := &MockFeatureFlagUseCase{ctrl: ctrl}
	mock.recorder = &MockFeatureFlagUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureFlagUseCase) EXPECT() *MockFeatureFlagUseCaseMockRecorder {
	return m.recorder
}

// Archive mocks base method.
func (m *MockFeatureFlagUseCase) Archive(ctx context.Context, actor, key, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Archive", ctx, actor, key, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Archive indicates an expected call of Archive.
func (mr *MockFeatureFlagUseCaseMockRecorder) Archive(ctx, actor, key, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Archive", reflect.TypeOf((*MockFeatureFlagUseCase)(nil).Archive), ctx, actor, key, reason)
}

// CreateFlag mocks base method.
func (m *MockFeatureFlagUseCase) CreateFlag(ctx context.Context, actor, key, name, purpose, owner string, safeDefault bool) (*domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFlag", ctx, actor, key, name, purpose, owner, safeDefault)
	ret0, _ := ret[0].(*domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFlag indicates an expected call of CreateFlag.
func (mr *MockFeatureFlagUseCaseMockRecorder) CreateFlag(ctx, actor, key, name, purpose, owner, safeDefault any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFlag", reflect.TypeOf((*MockFeatureFlagUseCase)(nil).CreateFlag), ctx, actor, key, name, purpose, owner, safeDefault)
}

// Evaluate mocks base method.
func (m *MockFeatureFlagUseCase) Evaluate(ctx context.Context, key, username string) domain.FeatureFlagDecision {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, key, username)
	ret0, _ := ret[0].(domain.FeatureFlagDecision)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockFeatureFlagUseCaseMockRecorder) Evaluate(ctx, key, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockFeatureFlagUseCase)(nil).Evaluate), ctx, key, username)
}

// GetFlagDetail mocks base method.
func (m *MockFeatureFlagUseCase) GetFlagDetail(ctx context.Context, key string) (*domain.FeatureFlagDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlagDetail", ctx, key)
	ret0, _ := ret[0].(*domain.FeatureFlagDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlagDetail indicates an expected call of GetFlagDetail.
func (mr *MockFeatureFlagUseCaseMockRecorder) GetFlagDetail(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlagDetail", reflect.TypeOf((*MockFeatureFlagUseCase)(nil).GetFlagDetail), ctx, key)
}

// ListAudit mocks base method.
func (m *MockFeatureFlagUseCase) ListAudit(ctx context.Context, key string, cursor, limit int) ([]domain.AuditRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAudit", ctx, key, cursor, limit)
	ret0, _ := ret[0].([]domain.AuditRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAudit indicates an expected call of ListAudit.
func (mr *MockFeatureFlagUseCaseMockRecorder) ListAudit(ctx, key, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAudit", reflect.TypeOf((*MockFeatureFlagUseCase)(nil).ListAudit), ctx, key, cursor, limit)
}

// ListFlags mocks base method.
func (m *MockFeatureFlagUseCase) ListFlags(ctx context.Context) ([]domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFlags", ctx)
	ret0, _ := ret[0].([]domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFlags indicates an expected call of ListFlags.
func (mr *MockFeatureFlagUseCaseMockRecorder) ListFlags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFlags", reflect.TypeOf((*MockFeatureFlagUseCase)(nil).ListFlags), ctx)
}

// SetEnvironment mocks base method.
func (m *MockFeatureFlagUseCase) SetEnvironment(ctx context.Context, actor, key string, env domain.Environment, mode domain.AvailabilityMode, percentage, revision int, reason string) (*domain.EnvironmentSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnvironment", ctx, actor, key, env, mode, percentage, revision, reason)
	ret0, _ := ret[0].(*domain.EnvironmentSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEnvironment indicates an expected call of SetEnvironment.
func (mr *MockFeatureFlagUseCaseMockRecorder) SetEnvironment(ctx, actor, key, env, mode, percentage, revision, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnvironment", reflect.TypeOf((*MockFeatureFlagUseCase)(nil).SetEnvironment), ctx, actor, key, env, mode, percentage, revision, reason)
}

// SetOverrides mocks base method.
func (m *MockFeatureFlagUseCase) SetOverrides(ctx context.Context, actor, key string, env domain.Environment, includes, excludes []string, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOverrides", ctx, actor, key, env, includes, excludes, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOverrides indicates an expected call of SetOverrides.
func (mr *MockFeatureFlagUseCaseMockRecorder) SetOverrides(ctx, actor, key, env, includes, excludes, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOverrides", reflect.TypeOf((*MockFeatureFlagUseCase)(nil).SetOverrides), ctx, actor, key, env, includes, excludes, reason)
}

// UpdateFlag mocks base method.
func (m *MockFeatureFlagUseCase) UpdateFlag(ctx context.Context, actor, key, name, purpose, owner string, safeDefault bool, reason string) (*domain.FeatureFlag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFlag", ctx, actor, key, name, purpose, owner, safeDefault, reason)
	ret0, _ := ret[0].(*domain.FeatureFlag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFlag indicates an expected call of UpdateFlag.
func (mr *MockFeatureFlagUseCaseMockRecorder) UpdateFlag(ctx, actor, key, name, purpose, owner, safeDefault, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFlag", reflect.TypeOf((*MockFeatureFlagUseCase)(nil).UpdateFlag), ctx, actor, key, name, purpose, owner, safeDefault, reason)
}
